Features/bo 13 edicion de sectores
ccsw-csd/bidoffice-server pull request #30
Opened 2022-09-14 09:20 UTC by ESDLH

2022-09-14 13:18 UTC, pajimene requested changes
Por favor, revisa los comentarios

2022-09-14 13:18 UTC, pajimene commented on src/main/java/com/ccsw/bidoffice/sector/SectorServiceImpl.java
> +    @ResponseBody
Esto creo que es innecesario, no devuelves nada, no necesitas un responseBody y menos en un Service esa anotación es de Controller

2022-09-14 13:18 UTC, pajimene commented on src/main/java/com/ccsw/bidoffice/sector/SectorServiceImpl.java
> +    @ResponseBody
Esto creo que es innecesario, no devuelves nada, no necesitas un responseBody y menos en un Service esa anotación es de Controller

2022-09-14 13:18 UTC, pajimene commented on src/main/java/com/ccsw/bidoffice/sector/SectorServiceImpl.java
> +            nameExists = this.sectorRepository.existsByName(dto.getName());
Esto es muy complicado, ¿4 métodos en repository para que?
Pongamos como ejemplo el name (para priority sería igual).
Deberías llamar a sectorRepository recuperar el sector por nombre -> getByName(xxx). 
Si viene a null es correcto. 
Si viene distinto de null tienes que comprobar si el id en BBDD es igual al id en el dto (el que estás editando). 
Si es igual, significa que estás haciendo un update de un registro en BBDD sobre él mismo y tiene name igual. Perfecto es ok.
Si es diferente, significa que estás haciendo un save de un registro diferente en BBDD sobre otro con el mismo name, entonces es ERROR.

De esta forma solo necesitas 2 métodos en repository y no 4.

2022-09-14 13:18 UTC, pajimene commented on src/main/java/com/ccsw/bidoffice/sector/model/SectorDto.java
> +    private Long priority;
¿Porque lo has cambiado a Long?

Lo había puesto yo a Integer porque se espera un número pequeño.
Por favor, déjalo en Integer.

2022-09-14 13:18 UTC, pajimene commented on src/main/java/com/ccsw/bidoffice/offer/OfferServiceImpl.java
> +    public boolean checkIfDateOfAllOfferAreInRange(SectorDto dto) {
Este método está mal diseñado funcionalmente y además no funciona correctamente.
Si viene un listado de fechas (por ejemplo 10 fechas) y la 9 da error, pero la 10 da ok, el resultado es OK cuando no debería ser así.
Además, se está trayendo todas las ofertas y se hace la comparación en java. Ahora tenemos 150 ofertas, pero cuando tengamos 15.000 ofertas esto irá lento.
La idea es que se lance una consulta en BBDD que devuelva las ofertas de ese sector cuya fecha de requestDate esté dentro de start y end. Se puede hacer con Specification y incluso con Derived Query Method (https://www.baeldung.com/spring-data-derived-queries#comparision-condition-keywords)

2022-09-16 11:13 UTC, ESDLH commented on src/main/java/com/ccsw/bidoffice/sector/SectorServiceImpl.java
> +            nameExists = this.sectorRepository.existsByName(dto.getName());
Creo que esto ya se discutió. Se hizo de esta manera (creo) para reducir la lógica del código y, al final, en todos los módulos del programa está así o de una forma muy similar.

2022-09-16 12:14 UTC, pajimene approved these changes

2022-09-16 12:15 UTC, pajimene commented on src/main/java/com/ccsw/bidoffice/sector/SectorServiceImpl.java
> +            nameExists = this.sectorRepository.existsByName(dto.getName());
Te lo paso, pero entonces vamos a cambiarlo en todos los sitios porque no es la manera óptima.

Creo una tarea para cambiarlo.

2022-09-16 12:20 UTC, merged