Features/filtrado oferta
ccsw-csd/bidoffice-server pull request #38
Opened 2022-10-11 11:18 UTC by aelmousa

Se han implementado las siguientes funcionalidades:

1. Creación de un filtrado mediante specification
2. Asignar fecha de ultima modificación a la hora de crear o modificar una oferta
3. Test unitarios y de integración

2022-10-11 13:22 UTC, pajimene requested changes
Revisa los cambios porfa

2022-10-11 13:22 UTC, pajimene commented on src/main/java/com/ccsw/bidoffice/offer/model/OfferItemListDto.java
> +    private LocalDateTime lastModification;
No le faltaría un converter???

@JsonDeserialize(converter = DateToLocalDateTimeConverter.class)

2022-10-11 13:22 UTC, pajimene commented on src/main/java/com/ccsw/bidoffice/offer/OfferServiceImpl.java
> +                this.beanMapper.map(dto.getStatus(), OpportunityStatusEntity.class), null));
A ver, para esto sirve la sobrecarga de métodos.

Queda muy feo invocar a un constructor con "null" y además, esto ocurre en el 90% de los casos....
La solución es que BinarySearchCriteria tenga dos constructores, uno acepta todos los valores actuales y otro acepta todos los valores menos el "value2" que por defecto lo pondrá a null.

De esta forma te evitar tener que llamar al constructor n veces pasandole un null

2022-10-11 13:22 UTC, pajimene commented on src/main/java/com/ccsw/bidoffice/common/criteria/BinarySearchCriteria.java
> +    public BinarySearchCriteria(String key, String operation, Object value, Object value2) {
Si revisas el comentario de OfferServiceImpl verás que he dicho crear dos constructores.

No repitas código. Con esto quiero decir que las líneas 14, 15 y 16 en los dos constructores son las mismas, así que para no repetir código, uno tendrá que llamar al otro con this(key, operation, value);

2022-10-17 07:54 UTC, aelmousa commented on src/main/java/com/ccsw/bidoffice/offer/model/OfferItemListDto.java
> +    private LocalDateTime lastModification;
En este caso no haría falta. El problema ocurría cuando enviábamos desde el front un Date por eso realizábamos un Deserialize (convierte de JSON a DTO). El OfferItemListDto únicamente es unidirectional, solo se envía del Back al front y nunca del front al back. Al enviarse del back al front ya es un LocalDateTime y no haría falta convertirlo.

2022-10-17 13:12 UTC, pajimene approved these changes

2022-10-18 07:02 UTC, merged